name: Release Generator
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4.1.4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Access MAPS_API_KEY
        env:
          MAPS_API_KEY: $
        run: echo MAPS_API_KEY=\"MAPS_API_KEY\" > ./local.properties

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }} 
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks

      - name: Build Release APK
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease --stacktrace

      - name: Get release file APK path
        id: releaseAPK
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release-artifacts
          path: ${{ steps.releaseAPK.outputs.apkfile }}

      - name: Release APK
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v1.0.3
          allowUpdates: true
          artifacts: ${{ steps.releaseAPK.outputs.apkfile }}
          
