name: Release Generator
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4.1.4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Access MAPS_API_KEY
        env:
          MAPS_API_KEY: $
        run: echo MAPS_API_KEY=\"MAPS_API_KEY\" > ./local.properties

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }} 
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign App APK
        uses: r0adkll/sign-android-release@v1.0.1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release-artifacts
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
